Cargo.toml
src/cli/account.rs
src/cli/mod.rs
src/errors.rs
src/lib.rs
src/main.rs
src/store/migrations.rs
src/store/mod.rs
src/store/store.sql

This PR sets up basic client structure. This consists of:
- Defining initial `Client` struct.
- Setting up basic database structure (via `Store` struct).
- Setting up basic CLI structure.
The idea is that we can execute a single end-to-end CLI command: "list accounts". This command retrieves a list of accounts from the sqlite database and prints them to the screen. The contents and formatting of what is printed is not important for this PR.

Set up basic client structure

---

Cargo.toml
src/lib.rs
src/mock.rs

Closes #53 
Minimal changes to calls to `mock_inputs` and `mock_new_account` to accomodate `miden-base` mock modifications. Add's `vm-processor` as a dev dependency.
(this PR has changes from #52 applied, it should be merged before this one)

fix: Mock functions input & output parameters

---

src/lib.rs
src/mock.rs
src/store/mod.rs

Closes https://github.com/0xPolygonMiden/miden-client/issues/55
Modify get_account_ids to correctly parse data retrieved from database. Added a couple of unit tests to verify it works as expected.

fix: Account id parsing

---

src/client/mod.rs
src/errors.rs
src/lib.rs
src/store/mod.rs

Closes #60 
Prevent adding a duplicate note tag to the tracking list by first checking if it's already present on the database.

fix: Prevent tracking duplicate note tags

---

Cargo.toml
src/cli/account.rs
src/cli/input_notes.rs
src/cli/mod.rs
src/cli/transactions.rs
src/client/accounts.rs
src/client/mod.rs
src/client/transactions.rs
src/errors.rs
src/lib.rs
src/mock.rs
src/store/mock_executor_data_store.rs
src/store/mod.rs
src/store/store.sql
src/store/transactions.rs

This PR adds 2 Client methods:
- `new_transaction()`,  which returns a `TransactionResult`
- `send_transaction()`, which takes a witness, proves it and sends it to the node, storing the transaction locally for tracking it further
Currently the endpoint has been mocked, as well as the `DataStore` that `TransactionExecutor` needs for running. When executing a transaction, we replace the data store with a new object that has what the transaction needs. In the future we need to make this work over our DB.
This can currently be tested by doing `cargo run --features testing --release -- mock-data` and then `cargo run --features testing --release -- transaction list`.

feat: Add transaction execution and proving

---

src/cli/input_notes.rs
src/client/notes.rs
src/client/transactions.rs
src/mock.rs
src/store/mock_executor_data_store.rs
src/store/notes.rs
src/tests.rs

In order to register notes that can be passed through a side channel, we need a method to import/export them

feat: Add method for exporting and importing notes

---

src/client/sync_state.rs
src/mock.rs

A [PR was merged](https://github.com/0xPolygonMiden/miden-node/pull/126) on miden-node which changed the path for `AccountId`. This PR fixes the 2 imports we had for it

Fix broken import path from miden node

---

src/mock.rs
src/store/mock_executor_data_store.rs
src/tests.rs

Apparently since [#405](https://github.com/0xPolygonMiden/miden-base/pull/405) from miden-base got merged the `mock_inputs` function now returns a TransactionInputs struct instead of a tuple. This PRs fixes the compilation errors that arised from that.

Fix for changes in mock_inputs from miden-base

---

src/cli/account.rs
src/client/accounts.rs
src/mock.rs
src/store/accounts.rs
src/store/state_sync.rs
src/store/store.sql
src/tests.rs

addresses #75 
I suggest only looking at commits [3a8f5fb](https://github.com/lambdaclass/miden-client/pull/9/commits/3a8f5fb191c3079bc0a3c5479968bde4877cc685) - [d1ff2a5](https://github.com/lambdaclass/miden-client/pull/9/commits/d1ff2a543a452cbc392345203b8d463a9f354dcd) since [8950643](https://github.com/lambdaclass/miden-client/pull/9/commits/895064370db5b3d8d2f1eda6adda9084402220d2) was already merged.
When creating an account, a seed is generated which is after used to create the account id. We were currently not storing it. For this PR we:
- Add a non nullable field to the accounts table called account_seed
- When creating new accounts (any kind of account), we also store the account seed
- On places where we used `let account = mock_account(None, Felt::ONE, None, &assembler);` I …

feat: persist account seed

---

src/store/accounts.rs

When testing with the cli, I found an error when running:
```bash
cargo run --release --features testing -- sync-state sync-state
store error: failed to parse data retrieved from the database: Integer -9151043079678472443 out of range at index 0
```
- read an i64 from rusqlite's `Row` and cast it to u64 afterwards (I saw this was being done for other ids)
It might take a few tries because it will depend on the generated faucet id. For each try do:
```bash
rm target/release/store.sqlite3
cargo run --release --features testing -- mock-data
cargo run --release --features testing -- account new fungible-faucet -t TEST -d 10 -m 10000
cargo run --release --features testing -- sync-state sync-state
```

fix: Fix endpoint to get account ids

---

Cargo.toml
src/cli/account.rs
src/cli/input_notes.rs
src/cli/mod.rs
src/cli/transactions.rs
src/client/accounts.rs
src/client/mod.rs
src/client/notes.rs
src/client/sync_state.rs
src/client/transactions.rs
src/errors.rs
src/lib.rs
src/mock.rs
src/store/accounts.rs
src/store/chain_data.rs
src/store/data_store.rs
src/store/mock_executor_data_store.rs
src/store/mod.rs
src/store/notes.rs
src/store/state_sync.rs
src/store/store.sql
src/store/transactions.rs
src/tests.rs

- Adds load-genesis command under the testing feature to load the 2 accounts [generated by the node binary](https://github.com/0xPolygonMiden/miden-node/blob/59984a5d4969053c55edf148c978a30b0ada23e9/README.md#generating-the-genesis-file)
- Adds `mint` subcommand to create, execute and send a mint transaction from a faucet account
- Adds `DataStore` implementation that goes to the client store to retrieve needed inputs
- Adds feature `mock` for using `mock` objects (RPC API and `DataStore`): Before this PR we had only the `testing` feature which enabled the same feature on the base repos and additionally enabled mock objects. We want to separate those in cases where we are trying to send a transaction to the node but decrease PoW costs
- Cleans up imports and some other functions/tests …

feat: Mint transaction and load accounts from Genesis files

---

src/client/sync_state.rs
src/client/transactions.rs
src/config.rs
src/errors.rs
src/mock.rs
src/store/accounts.rs
src/store/data_store.rs
src/store/mock_executor_data_store.rs
src/store/notes.rs

addresses #51
Note: on [061566d](https://github.com/0xPolygonMiden/miden-client/pull/87/commits/061566d053fdc00070d0d2bcf38fc1cdc9b75958) I used clippy with:
```bash
cargo clippy -- -D clippy::nursery -D clippy::all -D clippy::complexity -A clippy::use_self
```
and found out:
- a few functions that could be turned into const functions (I didn't do it for all of them, just the ones that might be called in const contexts)
- a few redundant clones and to_string

refactor: remove unwraps on options for sync rpc response

---

src/cli/transactions.rs
src/client/transactions.rs
src/mock.rs
src/store/accounts.rs
src/store/notes.rs
src/store/transactions.rs

addresses #83 
Reorders some code so that the database updates that are done after submitting a transaction successfully are done atomically.
I also made some functions to reuse code that was being run in transaction and non transaction contexts and avoid code duplication.

refactor: move account and note update to single transaction

---

src/cli/account.rs
src/cli/mod.rs

addresses #101 
I also added a load-account command so the user can add a single account by specifying the path. This is also doable by moving the account to a separate directory and using the load-accounts command, but thought this is a bit simpler for the user. I would consider changing it anyways.
Another thing I considered is adding a flag in `LoadAccounts` command to specify it's a single account instead of adding a separate `LoadAccount` command. I also would consider doing this instead

refactor: remove account indices argument, add command to load single account

---

src/store/state_sync.rs

[#263](https://github.com/0xPolygonMiden/crypto/pull/263) from miden-crypto got merged and it gives us a compilation error. Luckily the only change is the name of the `add` function of the PartialMmr. It got changed from `add` to `track`

fix: use new function name to add nodes with path to mmr

---

Cargo.toml
src/cli/transactions.rs
src/client/sync_state.rs
src/client/transactions.rs
src/main.rs
src/store/transactions.rs

addresses #82 
- adds tracing (currently used for logging only)
- adds tracing subscriber so that we see events when using the cli
- to do so, you must run the cli using `RUST_LOG=<level>` with `level` being the desired level (such as debug, info, trace, etc.) 
- changed all `println!` that were not part of the cli expected output so that they use the appropiate log function (`info!`, `debug!`, `warn!`, etc.)
We should be aware that `tracing` has some limitations. Particularly that `tracing_subscriber`'s fmt subscriber won't work on no_std nor wasm targets. Despite that there are two crates with subscribers that can we used for a wasm target:
- [tracing-wasm](https://github.com/old-storyai/tracing-wasm)
- [tracing-web](https://github.com/WorldSEnder/tracing-web), this one having been …

feat: add tracing 

---

README.md
src/cli/account.rs
src/cli/mod.rs
src/cli/sync_state.rs
src/cli/transactions.rs
src/client/accounts.rs
src/client/mod.rs
src/client/rpc_client.rs
src/client/sync_state.rs
src/client/transactions.rs
src/errors.rs
src/mock.rs
src/store/chain_data.rs
src/store/data_store.rs
src/store/mock_executor_data_store.rs
src/store/state_sync.rs
src/tests.rs

Closes #114.
This PR adds a new `TransactionTemplate::ConsumeAllNotes(AccountId)` to consume all stored committed notes for an account, and changes the previous existing template to consume a singular note, identified by the `NoteId`. 
In order to be able to consume multiple notes from arbitrary blocks, this PR also changes:
- When syncing, we now build the complete local view of the `PartialMmr` in order to correctly get new authentication nodes when applying the incoming changes. 
- For constructing the `TransactionInputs`, there is now a way to get authentication paths for arbitrary blocks in order to pass to the executor. 
This PR also refactors the sync process to make it more understandable and adds basic comments, but it will get better with some of the current outstanding PRs …

feat: Add consume all notes, refactor state sync

---

src/cli/account.rs
src/cli/input_notes.rs
src/cli/mod.rs
src/cli/sync.rs
src/cli/tags.rs
src/cli/transactions.rs
src/client/accounts.rs
src/errors.rs
src/store/accounts.rs
src/store/data_store.rs
src/store/migrations.rs
src/store/mod.rs
src/store/notes.rs
src/store/transactions.rs

I followed these guidelines:
- I first tried restricting pub functions as much as possible
- Then for each public function that was missing some doc comment,  I added it
- I didn't add a doc string for:
- Constructors
- Getters and setters
- Functions only used in tests

refactor: code cleanup and documentation

---

src/errors.rs

This PR changed the name of the file from `error.rs` to `errors.rs` breaking client: 
https://github.com/0xPolygonMiden/miden-node/pull/207
Should be fixed.

Fix breaking change of file naming on node

---

src/client/sync.rs
src/errors.rs
src/mock.rs
src/store/data_store.rs
src/tests.rs

This PR adds another test for the sync state but this will use the mocked data via `insert_mock_data` to check that we can still rebuild the required partial mmr

test: add sync state mmr tests

---

src/mock.rs
src/tests.rs

We had the test for the mint transaction ignored, because it fails with a `PhantomCallsNotAllowed` error. After some debugging I found out the way we were mocking the data store was wrong as it was returning input notes where it shouldn't. I found more errors after fixing that, so I ended up doing something similar to what is done in miden-tx to mock the fungible faucet account.

fix: fix mocked fungible faucet generation for tests

---

Cargo.toml

Both rusqlite and tonic had outdated versions in the client. 
Breaking compatibility with the node on some edge cases.

Bump rusqlite and tonic version

---

src/client/rpc_client.rs
src/mock.rs

This PR: https://github.com/0xPolygonMiden/miden-node/commit/78e5f5bb5e6c9da86bcf783ffc05aecb8f1d832c on the node-proto has added breaking changes to the miden-client 
Should be fixed by this PR.

Fix rpc error because of try_into() and into()

---

src/client/transactions.rs
src/store/transactions.rs

Merge after #161 (we may actually need to merge it to #161 before merging that one to main)
On [#442](https://github.com/0xPolygonMiden/miden-base/pull/442) from miden-base there was a breaking change introduced where the transaction execution now needs a `TransactionArgs` composed of the `tx_script` and the note args

fix: miden-base changes for note args

---

Cargo.toml
src/cli/account.rs
src/client/rpc_client.rs
src/client/sync.rs
src/client/transactions.rs
src/errors.rs
src/mock.rs
src/store/accounts.rs
src/store/notes.rs
src/store/transactions.rs

This PR updates the code to be compatible with new 0.8 version of the Winterfell.
This update mostly contains changes in `Felt` creation, since casting of `u64` to `FieldElement` was removed. It also updates the serialization and deserialization of the structs, which contain vectors of `Felt`s or `RpoDigest`s.

Update code to be compatible with Winterfell 0.8

---

Cargo.toml
src/cli/account.rs
src/cli/info.rs
src/cli/input_notes.rs
src/cli/mod.rs
src/cli/sync.rs
src/cli/tags.rs
src/cli/transactions.rs
src/client/accounts.rs
src/client/chain_data.rs
src/client/mod.rs
src/client/notes.rs
src/client/rpc/mod.rs
src/client/rpc/tonic_client.rs
src/client/rpc_client.rs
src/client/sync.rs
src/client/transactions.rs
src/errors.rs
src/lib.rs
src/mock.rs
src/store/mod.rs
src/tests.rs

closes #145 
This PR does 2 things:
- introduces the `NodeApi` trait, which provides an interface with the operations used by the client to interact with the node's rpc api
- the trait contains async functions which caused a warning to trigger which I disabled with `#[allow(async_fn_in_trait)]`
- changes the `Client` implementation to include said trait and make `RpcClient` and `MockRpcApi` implement `NodeApi`
- In this first iteration I went with using generics as I think it's usually recommended, it can be used in no_std / wasm targets without issues (I'm not sure about trait objects), and it's overall faster. However it made it more cumbersome to implement as I had to add generics all over the place, even in places like `client/transaction.rs` where I had to change `let random_coin = …

feat: add RPC client trait

---

.github/workflows/ci.yml

Currently the integration test job starts regardless of the result of the other jobs. It'd be better to wait until those finish since the integration test takes more resources and time and it'd be a waste to run it whilst some of the other steps fail.

enhancement: run integration test job after the test, clippy and fmt jobs

---

Cargo.toml

after [#479](https://github.com/0xPolygonMiden/miden-base/pull/479) got merged in miden-base build started to fail since we were compiling the mock crate without default features.
We should see in the future how we can go back to no default features in order to make the client no_std compatible

fix: use default features for mock crate after #479

---

Cargo.toml
src/store/mock_executor_data_store.rs
src/tests.rs

Fixes some compilation errors that pop up when running `cargo clippy --all --all-targets -- -D clippy::all -D warnings`. Apparently there was a refactor and now some assembly related structs were moved to miden-objects

fix: compilation errors

---

Makefile

By running the node on `debug`, we can compile it faster and performance doesn't take too much of a noticeable hit because proof verification is fast anyway. It shaves off about a minute according to some quick tests:
https://github.com/0xPolygonMiden/miden-client/actions/runs/8177753061/job/22360161677
https://github.com/0xPolygonMiden/miden-client/actions/runs/8179954642/job/22367088556?pr=212

tests: Run the node on `debug`

---

src/cli/account.rs

Fixes the `account show` table to correctly show all columns (previously, nonce was missing):
Ater:
Before:
We should also look into making these tables "safer" (eg, throw if number of columns and values do not match)

fix: Table columns on `account show`

---

src/cli/account.rs

When you run `miden-client account show` without providing an argument it fails saying that it's not somethig supported yet. Talked to @igamigo and came to the conclusion we don't need this currently and it's better to remove it.

refactor: make account id mandatory on cli command

---

src/store/sqlite_store/transactions.rs

Fixes a bug that caused transactions to not be detected as committed. It was found during #221. That PR adds some checks during integration tests to see that we mark the transaction status as expected but I think it's good to have the fix sooner than later

fix: store nullifier instead of id for transaction

---

Cargo.toml
Makefile.toml
clippy.toml
docs/library.md
src/cli/account.rs
src/client/accounts.rs
src/client/rpc/mod.rs
src/client/rpc/tonic_client.rs
src/client/sync.rs
src/client/transactions/mod.rs
src/client/transactions/transaction_request.rs
src/mock.rs
src/store/mod.rs
src/store/sqlite_store/accounts.rs
src/store/sqlite_store/mod.rs
src/store/sqlite_store/sync.rs
src/store/sqlite_store/transactions.rs
tests/integration/main.rs

This PR introduces a few things:
- Adds a new param to the CLI for the `account new` command, `--storage-mode=onchain,offchain(default)` that enables the creation of onchain accounts
- Adds to the node rpc client a `get_account_updates` trait function. This function takes an account ID and fetches the `GetAccountDetails` endpoint on the node added on [#294](https://github.com/0xPolygonMiden/miden-node/pull/294) from miden-node (and previous PRs)
- Updates the sync behavior
- When doing a sync we check the account updates in two ways (always doing so **for tracked accounts**).
- First, validating that the updated offchain account hashes match the ones of our client
- Second, checking the updated onchain accounts, if the hash does not match ours that means it's outdated and thus we'll use …

feat: Add account details endpoint

---

README.md

There is a missing parameter in one of the client tutorial steps. The `miden-client tx new consume-notes command` should receive the `<input-note-ID>`.

Fix README tutorial

---

src/cli/account.rs

I noticed that the command `miden-client account show <SOME_ACCOUNT_ID> -k` is failing due to the serialized `SecretKey` not fitting in a `sizeof(SecretKey)` bytes long array.
Using the CLI:
- create any regular account (e.g. `miden-client account new basic-immutable`)
- show the account keys with `miden-client account show <ACCOUNT_ID> -k`. This'll trigger the error

fix: use correct array size for SecretKey

---

docs/cli-config.md
docs/cli-reference.md
miden-client.toml
src/cli/input_notes.rs
src/cli/mod.rs
src/client/mod.rs
src/client/notes.rs
src/client/transactions/mod.rs
src/errors.rs
src/store/sqlite_store/mod.rs
tests/integration/main.rs

- After https://github.com/0xPolygonMiden/miden-base/pull/562, implements debug mode.
- Adds a new method for compiling note scripts, so that users do not need to instantiate the assembler separately. This way if the client is created with debug mode, all scripts compiled and executed by it should show debug output.
- Changes return type of `Client::new()` removing the unnecessary `Result<>`
- Smaller renames/refactors
Follow-up work: 
- Create a test that confirms that debug output is shown

feat: Implement debug mode

---

tests/integration/main.rs

closes #239 (The issue says it's not necessary to do an integration test but I'd rather have real blocks stepping over. Plus mocking all the intermediate sync state responses would add a lot of complexity IMHO)
On #219 we added the Pay To ID with Recall transaction along with an integration test for the "happy path" (sender executes the tx, target receives it and consumes it).
On this PR we check the following cases that were left out (The P2IDR tx has one output note which handles the funds transfer):
- The sender tries to reclaim (consume) the note too early and fails
- The sender tries to consume the note after waiting for the recall height and does so successfully
- The sender consumes the note and the target can't consume the note anymore

test: validate all other p2idr cases

---

tests/integration/main.rs

Now that the client can compile note scripts, we have to update the tests as it serves as reference for some users and this would be the more correct way to do it (to take advantage of the debug mode)

Update test to use new client function

---

src/store/sqlite_store/accounts.rs

closes #286
Refactored the `get_account` function to build the account from a single big query instead of multiple small ones.

refactor: get account from a single store query

---

CHANGELOG.md
docs/cli-config.md
miden-client.toml
src/cli/init.rs
src/cli/input_notes.rs
src/cli/mod.rs
src/client/rpc/tonic_client.rs
src/config.rs
tests/config/miden-client.toml
tests/integration/main.rs

Adds a timeout config to the rpc configuration. This is a small breaking change as now `TonicRpcClient` constructor takes the full rpc config. I checked [tonic endpoint's documentation](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html) and didn't see any other relevant settings.

feat: add timeout to rpc config

---

CHANGELOG.md
src/store/sqlite_store/notes.rs

Currently, we ignore note scripts if they already exist in the `note_scripts` table. This isn't necessarily wrong, but it makes it akward to debug notes because if you want to add a `debug.stack` instruction for example, the note script hash doesn't change and thus if you already had the note script on the db the change won't go through. Because of that, you end up needing to clear the db (or at least the existing row) on each change and it slows down the debug process

fix: replace known note script in note_scripts if exists

---

src/client/sync.rs

closes #252
One of the conditions to check if a transaction was commited or not is whether it's output notes are also commited. This check was disabled because we thought it didn't work. We later discovered that it was not the case from the discussion in the issue. The previous PR (#273) was closed because of this.

Re enable check on output notes for transactions

---

docs/cli-reference.md
src/cli/transactions.rs

closes #257 
- Shows the TX details before proving and submitting the tx [f0fb419](https://github.com/0xPolygonMiden/miden-client/pull/290/commits/f0fb4194e8a11bbb3a224e2bdc749413e5dd6c70)
- Adds a "--force" flag to the new transaction command to skip the confirmation step (ideal for non-interactive environments) [b712ede](https://github.com/0xPolygonMiden/miden-client/pull/290/commits/b712ede241784ab7550f3deaa43b6f2457b7f950)
You can start from either a fresh client or an existing one. To test this change, you can run any transaction (i.e `miden-client tx new ...`) and check that it asks for confirmation and it prints a summary of the changes applied to the account. Enusure that if you submit a "y" or "Y" the transaction gets proven and sent to the node, and doesn't do anything else …

feat: ask confirmation before submitting transaction

---

src/cli/account.rs
src/cli/mod.rs
src/cli/transactions.rs

on #274 we allowed partial IDs on commands, however we missed an interaction. We sometimes want to do operations against accounts not tracked by the client (e.g p2id, i don't necessarily have the target account in my client).
To overcome this we change a little bit
(on `next` should fail and in this branch it shouldn't)
- create a faucet account
- sync
- on a separate client, create a basic account stored offchain and copy its account id (let's call it `x`)
- go back to the starting client and do a mint transaction with `x` as the target account

fix: try to parse account id before searching on db

---

CHANGELOG.md
src/client/notes.rs
src/client/transactions/mod.rs
src/store/note_record/input_note_record.rs
src/store/note_record/output_note_record.rs
src/store/sqlite_store/notes.rs
src/store/sqlite_store/store.sql
src/store/sqlite_store/transactions.rs
tests/integration/main.rs
tests/integration/onchain_tests.rs

This is a better implementation for the problem addressed in PR #325 using the ideas proposed in [this discussion](https://github.com/0xPolygonMiden/miden-client/pull/325#issuecomment-2099305918).

feat: add a way to get the consumer account of a note

---

CHANGELOG.md
src/cli/info.rs
src/cli/mod.rs
src/cli/notes.rs
src/client/note_screener.rs
src/client/sync.rs
src/client/transactions/transaction_request.rs
src/store/note_record/mod.rs

closes #314 
This PR focuses on the last commands that needed improved output. Specifically:
- `info` now prints more information abount the client.
- `notes list` now shows the note status with additional information like commit height and consumer account.
- `notes show` is better styled and shows the information in a clearer manner.
Some screenshots:
`info` command
`notes list` command
`notes show` command (with all flags)

feat: add extra cli output for certain commands

---

docs/cli-config.md
docs/cli-reference.md
docs/library.md

updates the documentation after PRs for #314 and some others got merged

docs: update docs from changes to CLI

---

CHANGELOG.md
src/client/mod.rs
src/client/notes.rs
src/client/rpc/mod.rs
src/client/rpc/tonic_client.rs
src/client/sync.rs
src/errors.rs
src/mock.rs
src/store/mod.rs
src/store/sqlite_store/chain_data.rs
src/store/sqlite_store/mod.rs
src/store/sqlite_store/sync.rs
tests/integration/common.rs
tests/integration/main.rs

This PR implements the new `GetBlockHeaderByNumber` RPC changes. We can now ask for authentication data for past blocks, so whenever we import a note with `verify`, we can download the block header and authentication data as well.

feat: Use RPC to get MMR data for past blocks on note importing

---

CHANGELOG.md
src/cli/import.rs
src/cli/new_transactions.rs
src/cli/notes.rs
src/client/transactions/mod.rs
src/mock.rs
src/tests.rs
tests/integration/common.rs

Closes #330 
**This is a breaking change.**
This PR separates the proving from the submition of a new transaction in the client. This lets us have separate messages in the cli with the duration of each step.

feat: split proving and submitting message

---

CHANGELOG.md
src/cli/account.rs
src/cli/notes.rs
src/store/sqlite_store/notes.rs

closes #332 
The `notes --list` command showed both input and output in the same table. The table was also a bit crowded. 
This PR fixes this by separating the notes into two side by side tables that only show the ID and status of a note. 
If the user wants to see more information about a certain note they can run `miden notes --show <id>`.
Additional fixes:
- The `miden account` table is also simplified to only show ID, type and nonce. 
- Fixed a bug where the `consumer_account_id` was only updated on input notes.
Screenshot of the new table (ignore the fact that some consumers are not known, that is the bug that was fixed):

refactor: simplify and separate note list

---

CHANGELOG.md
src/cli/account.rs
src/cli/export.rs
src/cli/import.rs
src/cli/mod.rs
src/cli/new_account.rs
src/cli/utils.rs

closes #351 
Now when creating a new wallet account or importing a wallet account, if no account is set as the default one the created / imported will be set as the default one.
I also noticed we were using `load_config_file` much more than `load_config` so I kept the last one private and changed to `load_config_file` on main.

feat: set created/imported account as default if none is set

---

src/cli/mod.rs
src/cli/new_account.rs
src/cli/notes.rs
src/lib.rs
tests/integration/cli_tests.rs
tests/integration/common.rs
tests/integration/custom_transactions_tests.rs
tests/integration/main.rs
tests/integration/onchain_tests.rs
tests/integration/swap_transactions_tests.rs

closes #280 
Tested with:
I think testing against real use cases instead of just looking at the api will avoid some missing re-exports problems. We can still iterate on this as users of the crate can decide when they remove the dependency and just use the re-exports instead.

feat: add re exports from base used in public api

---

.github/workflows/build.yml
Makefile
README.md

We missed a [comment](https://github.com/0xPolygonMiden/miden-client/pull/402#discussion_r1662964348) on #401 and currently the build for wasm is broken. This PR fixes that and introduces a `build` workflow to the CI that runs both `make build` and `make build-wasm`

fix: update build-wasm target from Makefile

---

CHANGELOG.md
crates/rust-client/src/lib.rs
crates/rust-client/src/transactions/mod.rs
crates/rust-client/src/transactions/transaction_request.rs
tests/integration/asm/custom_p2id.masm
tests/integration/custom_transactions_tests.rs

addresses: #398 
note: when I tried debugging the note script I noticed we were never creating the `TransactionExecutor` in debug mode and so debug statements weren't being executed. I think we previously had it and deleted it by mistake. [7793881](https://github.com/0xPolygonMiden/miden-client/pull/422/commits/7793881ea426703062d9bf735f3e18cdde9453c1) restores it

feat: add advice map to transaction request

---

.github/workflows/build.yml

The workflow name was wrong and thus the badge was generating incorrectly (also was annoying to differentiate workflows in the actions section of github)

fix: rename workflow name to build instead of test

---

CHANGELOG.md
crates/rust-client/src/notes/mod.rs
crates/rust-client/src/store/note_record/input_note_record.rs
crates/rust-client/src/store/note_record/mod.rs
crates/rust-client/src/store/note_record/output_note_record.rs

Addresses [this comment](https://github.com/0xPolygonMiden/miden-client/pull/375#discussion_r1646138611)
This PR looks to refactor the creation of `NoteRecordDetails` from `Note` and `NoteDetails` by impementing `From` conversions.

refactor: Add conversions for `NoteRecordDetails`

---

docs/install-and-run.md

The actual binary package is called 'miden-cli', whilst 'miden-client' is just the library. Therefore trying to run 'cargo install miden-client --features concurrent,executable,testing' returns an error that miden-client is a library and has no binaries.

Fix install command in docs

---

crates/rust-client/build.rs

closes #429 
The `build.rs` had problems when executing inside `docs.rs`. This PR looks to skip the update of generated files if the env var `DOCS_RS` is set which means it is currently building the docs.

fix: don't update generated files in docs.rs

---

CHANGELOG.md
tests/integration/main.rs
tests/integration/swap_transactions_tests.rs

addresses #391. (The PR is already reviewable but I think this will be included in the following release).
In some tests we do some assertions with `client.get_input_notes(filter).unwrap()` and checking the length of it. While in most cases that is enough, it will sporadically fail If the node running the integration test has public notes belonging to another account with the same account id prefix (the one used to create the note tag). In order to mitigate it, we do a filter by account_id to ensure the note we want is there (there might be others, we won't care too much). In the case of swap tests, I also used `get_consumable_notes` since in that situation we wanted to consume the notes anyways.

testfix: flaky tests fix attempt

---

CHANGELOG.md
bin/miden-cli/src/commands/new_transactions.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transactions/mod.rs
tests/integration/common.rs
tests/integration/main.rs

Closes #439 
BREAKING CHANGES: change transactions API.
As indicated in [the issue](https://github.com/0xPolygonMiden/miden-client/issues/439): merges prove and submit transaction methods into submit, logs the time that takes each step, updates method doc and update calls.

refactor(transactions)!: Merge prove and submit transaction methods

---

Makefile

Small fix in `make check` documentation.
Change documentation in `check` targets, move every comment to 1st person.
Closes #460

docs: fix comment in Makefile

---

CHANGELOG.md
Makefile
bin/miden-cli/src/commands/export.rs
crates/rust-client/Cargo.toml
crates/rust-client/src/mock.rs
crates/rust-client/src/notes/mod.rs
crates/rust-client/src/rpc/domain/notes.rs
crates/rust-client/src/rpc/tonic_client/generated/account.rs
crates/rust-client/src/rpc/tonic_client/generated/note.rs
crates/rust-client/src/rpc/web_tonic_client/generated/account.rs
crates/rust-client/src/rpc/web_tonic_client/generated/note.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transactions/request.rs
crates/rust-client/src/transactions/script_builder.rs
crates/web-client/src/export.rs
tests/integration/custom_transactions_tests.rs
tests/integration/main.rs
tests/integration/swap_transactions_tests.rs

closes #466 
This PR implements serialization to and from bytes for `TransactionRequest`. Some tests are also added to verify a correct serialization.
When comparing if the deserialized `TransactionRequest` is the same, we are ommitting the `ProgramAst` code as we found that they were not the same. The difference was mentioned by [a comment](https://github.com/0xPolygonMiden/miden-vm/blob/9abd8d17483dc7a3b23ebb72ab30b86426ddf19d/assembly/src/ast/imports.rs#L175-L176) in `miden-vm`, which was later removed in v0.10. Once the client is updated to the new vm version we can add back the check to see if the problem persists.

feat: add serialization for `TransactionRequest` 

---

Makefile
crates/rust-client/src/transactions/mod.rs
tests/integration/main.rs

Adds an integration test that runs multiple transactions on the same block.
Closes #461 .

test: multiple transaction on the same block

---

CHANGELOG.md
bin/miden-cli/src/commands/export.rs
bin/miden-cli/src/commands/import.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/notes/mod.rs
crates/rust-client/src/rpc/mod.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/rpc/web_tonic_client/mod.rs
crates/rust-client/src/tests.rs
crates/web-client/src/export.rs
tests/integration/main.rs
tests/integration/swap_transactions_tests.rs

Follows up #405 
~~**_### Do not merge until https://github.com/0xPolygonMiden/miden-base/pull/823 is merged._**~~
This PR adds support for committed notes from "the past" (in the client's perspective).
TO DOs:

feat: import committed notes from older blocks that current

---

Cargo.toml
Makefile
crates/rust-client/Cargo.toml
crates/web-client/Cargo.toml
tests/Cargo.toml

chore: point `miden-base` dependencies to `next` branch

---

CONTRIBUTING.md
README.md
bin/miden-cli/README.md
docs/api-docs.md
docs/examples.md
mkdocs.yml

This PR closes https://github.com/0xPolygonMiden/miden-client/issues/282 and changes the client docs sections a bit. The goal is to explain the client design, the client as library and the client's CLI.
The new proposed structure is 
- Overview:
- Overview: index.md
- Features: features.md
- Design:
- Overview: design.md
- API docs: api-docs.md
- Miden client library: 'library.md'
- Miden CLI:
- Configuration: 'cli-config.md'
- Reference: 'cli-reference.md'
- Install and run: install-and-run.md
- Examples: 'examples.md'
Whereas `api-docs.md` links to https://docs.rs/miden-client/latest/miden_client/

Revisit client docs sections organization

---

Cargo.toml
Makefile
bin/miden-cli/src/commands/account.rs
bin/miden-cli/src/commands/new_transactions.rs
crates/rust-client/src/accounts.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/rpc/domain/blocks.rs
crates/rust-client/src/rpc/mod.rs
crates/rust-client/src/rpc/tonic_client/generated/block.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/rpc/web_tonic_client/generated/block.rs
crates/rust-client/src/rpc/web_tonic_client/mod.rs
crates/rust-client/src/store/sqlite_store/accounts.rs
crates/rust-client/src/store/sqlite_store/chain_data.rs
crates/rust-client/src/store/web_store/accounts/mod.rs
crates/rust-client/src/store/web_store/accounts/utils.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transactions/request.rs
crates/web-client/src/account.rs

Updates the client to use `miden-base`'s `next` (it uses a temporary fork of miden-base `next` that fixes what https://github.com/0xPolygonMiden/miden-base/pull/875 also fixes, until that PR is merged)

Fix build after storage changes

---

Cargo.toml
Makefile
crates/rust-client/src/mock.rs
crates/rust-client/src/store/sqlite_store/accounts.rs

After merging https://github.com/0xPolygonMiden/miden-base/pull/875, we no longer need the temporary fixes.

chore: Go back to next on miden-base

---

crates/rust-client/Cargo.toml
crates/rust-client/src/accounts.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/rpc/domain/notes.rs
crates/rust-client/src/store/sqlite_store/accounts.rs
crates/rust-client/src/tests.rs

Closes #455 
This removes any mocking code and uses mocking code from dependencies. It also simplifies and makes the Mock RPC backend much more readable/usable.

refactor: Simplify mock code

---

crates/web-client/package.json
crates/web-client/rollup.config.js

This PR adds a flag to remove wasm optimizations when running the `npm run build` command when testing. This marginally increases the individual test time but it greatly reduces the time to build the wasm files which is a net positive.

feat: improve build time for testing

---

CHANGELOG.md
crates/rust-client/src/accounts.rs
crates/rust-client/src/notes/import.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/sqlite_store/mod.rs
crates/rust-client/src/store/sqlite_store/store.sql
crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/store/sqlite_store/transactions.rs
crates/rust-client/src/store/web_store/js/accounts.js
crates/rust-client/src/store/web_store/js/schema.js
crates/rust-client/src/store/web_store/js/sync.js
crates/rust-client/src/store/web_store/mod.rs
crates/rust-client/src/store/web_store/sync/js_bindings.rs
crates/rust-client/src/store/web_store/sync/mod.rs
crates/rust-client/src/store/web_store/sync/models.rs
crates/rust-client/src/store/web_store/transactions/mod.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/sync/tags.rs
crates/rust-client/src/tests.rs
crates/web-client/src/tags.rs
crates/web-client/test/mocha.global.setup.mjs
crates/web-client/test/tags.test.ts
crates/web-client/yarn.lock
tests/integration/main.rs

closes #484 
This PR looks to refactor the way we deal with note tags in the client. Previously, the note tag list sent to the node was built from zero each time, joining tags derived from accounts+notes and tags added by the user. This refactor creates a new table in the store that stores all of the tracked tags, including those derived from accounts and notes.
A new struct is introduced to represent the stored tags:
```rust
/// Represents a note tag of which the Store can keep track and retrieve.
pub struct NoteTagRecord {
pub tag: NoteTag,
pub source: NoteTagSource,
}
/// Represents the source of the tag. This is used to differentiate between tags that are added by
/// the user and tags that are added automatically by the client to track notes .
pub enum NoteTagSource { …
```

feat: store note tags in separate table

---

CHANGELOG.md
crates/web-client/package.json
crates/web-client/src/sync.rs

Small PR to add error handling for sync state so that js client doesnt silently fail

fix: Error handling for web client sync state

---

CHANGELOG.md
crates/rust-client/src/rpc/tonic_client/generated/requests.rs
crates/rust-client/src/rpc/tonic_client/generated/responses.rs
crates/rust-client/src/rpc/web_tonic_client/generated/requests.rs
crates/rust-client/src/rpc/web_tonic_client/generated/responses.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transactions/mod.rs
crates/rust-client/src/transactions/request.rs
crates/rust-client/src/transactions/script_builder.rs

closes #544 
Should be merged after https://github.com/0xPolygonMiden/miden-base/pull/925
This PR adds support for transaction expiration delta in `TransactionRequest`.

feat: add expiration delta to `TransactionRequest`

---

bin/miden-cli/src/tests.rs

After https://github.com/0xPolygonMiden/miden-node/pull/517 got merged, the genesis account name changed from `account0.mac` to `faucet.mac`

fix: genesis account name

---

CHANGELOG.md
crates/web-client/Cargo.toml
crates/web-client/package.json
crates/web-client/src/lib.rs
crates/web-client/src/models/input_note_record.rs

Bringing in the ability to create a web client with a remote proving url 
Tested this manually via spinning up a local proving node and pointing to it in some integration tests. 
On the backlog is to create a fully fledged integration test for this. The reason why its not included in this PR is that it would require us to set up a Makefile command to spin up a remote prover within the github actions context and then setup our test infra to toggle between the clients. 
This will be a fast-follow on our backlog, but to enable delegated proving for the Devcon wallet, putting up the PR in its current state.

feat: Adding remote proving + improving note models

---

CHANGELOG.md
crates/web-client/test/transactions.test.ts
crates/web-client/test/webClientTestUtils.ts
crates/web-client/yarn.lock

This PR adds integration tests for the `get_transactions` and `compile_tx_script` web client calls in `transactions.rs`.

Transaction Tests

---

CHANGELOG.md
crates/web-client/package.json
crates/web-client/yarn.lock

Some dependency bumps are required to get the WASM in a compatible state with the current next of miden-node / miden-base

chore: Rebuild WASM + version bump

---

crates/rust-client/src/store/web_store/notes/mod.rs

In #559 we changed the way `NoteFilter::List` behaved when it didn't find every listed note. Originally it returned an error but in that PR we changed it so that it just returned an incomplete list. The sqlite store was updated but we didn't remove the error from the idxdb store.
The test was flaky because it was failing here: 
https://github.com/0xPolygonMiden/miden-client/blob/db8454a08b8e8723b8e7b6cf7a77b7c78c036f0c/crates/rust-client/src/sync/mod.rs#L290-L294 
Where the notes returned by the node may or may not exist in the store. Depending on the state of the node at a given moment, it may return notes that are not relevant to the client.

fix: remove `NoteFilter::List` error from web store

---

CHANGELOG.md
crates/web-client/test/global.test.d.ts
crates/web-client/test/mocha.global.setup.mjs
crates/web-client/test/new_transactions.test.ts
crates/web-client/test/notes.test.ts
crates/web-client/test/webClientTestUtils.ts

This PR adds a slight optimization to the web client integration tests by checking to see whether transactions have been committed via a sync loop as opposed to using a fixed 20-second timeout across all tests. This should result in a slight speedup on the overall timing of the tests. 
Snapshot of run on this PR after change:
Snapshot of random PR before change: 
so seems to have a good improvement. Will continue to look for areas of optimization to continue shaving down the web client integration test times

Added Sync Loop to Web Client Integration Tests

---

mkdocs.yml

Try to fix the [Miden client -> Install and run](https://docs.polygon.technology/miden/miden-client/install-and-run.md') page 404 error.

fix doc 404 error

---

CHANGELOG.md
bin/miden-cli/src/commands/new_transactions.rs
bin/miden-cli/src/lib.rs
bin/miden-cli/src/tests.rs
crates/rust-client/src/lib.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/transactions/mod.rs
crates/web-client/src/lib.rs
crates/web-client/src/new_transactions.rs
tests/Cargo.toml
tests/integration/common.rs
tests/integration/main.rs

closes #592 
This PR is an alternative approach to #598 which is mentioned in the original issue. I think this approach looks better when compared to #598 as it doesn't change the interface of the `submit_transaction` function (which is used a lot).

feat: add per transaction prover

---

README.md

The spelling of "miden-clinet" is incorrect, it should be "miden-client". This could lead to a broken link.

docs: The spelling of "miden-clinet" is incorrect, it should be "miden-client". This could lead to a broken link.

---

CHANGELOG.md
crates/web-client/js/index.js
crates/web-client/js/types/index.d.ts
crates/web-client/package.json
crates/web-client/src/models/note_recipient.rs
crates/web-client/test/global.test.d.ts
crates/web-client/test/mocha.global.setup.mjs
crates/web-client/test/new_transactions.test.ts
crates/web-client/test/notes.test.ts
crates/web-client/test/webClientTestUtils.ts

Per the [issue filed here](https://github.com/0xPolygonMiden/miden-client/issues/664), it was possible to hit a `DuplicateOutputNote` Error from the Web Client by creating a custom transaction with multiple output notes that were identical. The reason for this is creating a `NoteRecipient` currently uses the [same default seed ](https://github.com/0xPolygonMiden/miden-client/blob/86cba1512f834a9269fe4f2af7569d96a1d12e75/crates/web-client/src/models/note_recipient.rs#L20) every time so if everything else in the notes were the same, there would be nothing to differentiate the two.
The fix just exposes an additional `serial_num: &Word` parameter to the `Note Recipient` constructor of the Web Client API so that the user can pass in a seed and differentiate notes with otherwise identical …

Added Serial Num Parameter to Note Recipient Constructor in the Web Client

---

Cargo.lock
Cargo.toml
Makefile
crates/rust-client/Cargo.toml
crates/web-client/Cargo.toml

This PR does not prepare for the 0.7 release but points to the newer versions of the crates

chore: Point to `0.7` versions of crates

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/miden-cli/Cargo.toml
bin/miden-cli/src/commands/account.rs
bin/miden-cli/src/commands/export.rs
bin/miden-cli/src/commands/import.rs
bin/miden-cli/src/commands/init.rs
bin/miden-cli/src/commands/new_account.rs
bin/miden-cli/src/commands/new_transactions.rs
bin/miden-cli/src/commands/notes.rs
bin/miden-cli/src/commands/sync.rs
bin/miden-cli/src/commands/tags.rs
bin/miden-cli/src/commands/transactions.rs
bin/miden-cli/src/errors.rs
bin/miden-cli/src/faucet_details_map.rs
bin/miden-cli/src/info.rs
bin/miden-cli/src/lib.rs
bin/miden-cli/src/main.rs
bin/miden-cli/src/utils.rs
crates/rust-client/Cargo.toml

closes #369 
Current state of the errors:

feat: improve errors in the CLI

---

docs/cli-reference.md

The example contained the correct form already.

docs: Hypen instead of underscore

---

bin/miden-cli/config/miden-client-rpc.toml
bin/miden-cli/src/tests.rs
tests/config/miden-client-rpc.toml
tests/integration/common.rs

fix: integration tests with devnet

---

Cargo.lock
bin/miden-cli/src/commands/sync.rs
crates/rust-client/src/account.rs
crates/rust-client/src/note/import.rs
crates/rust-client/src/note/mod.rs
crates/rust-client/src/rpc/domain/nullifier.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/sqlite_store/mod.rs
crates/rust-client/src/store/sqlite_store/note.rs
crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/store/web_store/js/sync.js
crates/rust-client/src/store/web_store/mod.rs
crates/rust-client/src/store/web_store/note/utils.rs
crates/rust-client/src/store/web_store/sync/js_bindings.rs
crates/rust-client/src/store/web_store/sync/mod.rs
crates/rust-client/src/sync/block_header.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/sync/state_sync.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transaction/mod.rs
crates/web-client/package-lock.json
crates/web-client/src/models/sync_summary.rs
tests/integration/main.rs
tests/integration/onchain_tests.rs

This version is still a WIP.
The idea is to remove the sync steps from the interface of the `StateSync` so that the user doesn't have to deal with them and the sync is shown as a single step process.
After some bug fixing, the rust tests are passing so this version works! It's a bit messy and the documentation is now outdated. Will be working on this next but the main changes can be discussed:
The main change with this new functionality is that we relied on store to persist the updates on each step but if we remove the steps, we need to store the intermediate states of notes on each step and update them accordingly without storing them. The changes made in `state_sync.rs` can be summarized as:
- `NoteUpdates`: Instead of being 4 vectors of notes, now it's 2 maps (one for input and another …

refactor: remove steps from `StateSync` interface

---

CHANGELOG.md
crates/rust-client/src/sync/mod.rs

This PR implements the Serializable and Deserializable traits for the SyncSummary struct, as needed for #720.

feat: implement Serializable and Deserializable for SyncSummary

---

bin/miden-cli/src/commands/sync.rs
crates/rust-client/src/note/mod.rs
crates/rust-client/src/store/sqlite_store/note.rs
crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/store/web_store/note/utils.rs
crates/rust-client/src/store/web_store/sync/mod.rs
crates/rust-client/src/sync/block_header.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/sync/state_sync_update.rs
crates/rust-client/src/transaction/mod.rs
crates/web-client/src/models/sync_summary.rs
tests/integration/main.rs

This is an auxiliary PR to reduce the review changes in https://github.com/0xPolygonMiden/miden-client/pull/650
These are mostly struct field refactors that are used in the `StateSync` component PR but can be reviewed separately.

refactor: update structs for `StateSync` component

---

bin/miden-cli/src/lib.rs
bin/miden-cli/src/tests.rs
crates/rust-client/Cargo.toml
crates/rust-client/src/lib.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/note/import.rs
crates/rust-client/src/rpc/mod.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/rpc/web_tonic_client/mod.rs
crates/rust-client/src/sync/block_header.rs
crates/rust-client/src/tests.rs
crates/web-client/src/lib.rs
docs/library.md
tests/integration/common.rs
tests/integration/main.rs

This is an auxiliary PR to reduce the review changes in #650 
The rpc_api in the client was changed from Box to Arc so it can be shared with the component. This also means that I had to change the base struct to give it interior mutability.

feat: give interior mutability to rpc client

---

Cargo.lock
Cargo.toml
Makefile
bin/miden-cli/src/commands/export.rs
bin/miden-cli/src/commands/import.rs
bin/miden-cli/src/commands/new_transactions.rs
crates/rust-client/Cargo.toml
crates/rust-client/src/account.rs
crates/rust-client/src/rpc/generated/nostd/requests.rs
crates/rust-client/src/rpc/generated/nostd/responses.rs
crates/rust-client/src/rpc/generated/std/requests.rs
crates/rust-client/src/rpc/generated/std/responses.rs
crates/web-client/src/import.rs
crates/web-client/src/lib.rs
crates/web-client/src/models/provers.rs
tests/config/miden-node.toml

This also requires a [specific branch](https://github.com/0xPolygonMiden/miden-node/pull/689) from the node for now, because the node was also still using 0.7.

chore: Use `miden-base`'s next

---

CHANGELOG.md
crates/rust-client/src/account/mod.rs
crates/rust-client/src/errors.rs
tests/integration/common.rs
tests/integration/onchain_tests.rs

feat: add `import_account_by_id`

---

CHANGELOG.md
crates/web-client/js/index.js

In https://github.com/0xPolygonMiden/miden-client/pull/720, the web client was modified to offload certain heavy computation to web workers. It failed, however, to handle the case where it executes in environments where web workers are not available. This PR is a follow-up that handles this case. In this scenario, calls are forwarded as normal to the underlying WASM web client.

Web Client Fix: Handle Case Where Web Workers Not Available

---

Makefile

The last commit on the node changed the `StateSync` endpoint. The fix for this is still a WIP, in the meantime we can downgrade the node used in the CI so that the integration tests work again.

chore: node version downgrade

---

CHANGELOG.md
crates/rust-client/src/builder.rs
crates/rust-client/src/errors.rs
crates/rust-client/src/lib.rs
tests/integration/main.rs

This PR introduces a new client builder to the Rust client, streamlining the initialization process and reduces the amount of boilerplate code when getting started with a Miden dApp. With the new client builder, setting up a Miden dApp in Rust becomes significantly easier. Personally, this was one of the features I really wanted to have as I was building the tutorial code examples.
By integrating this feature, we lower the barrier to entry and reduce the lines of code needed to deploy and interact with smart contracts and notes. For context, our [Miden dApp tutorials](https://0xpolygonmiden.github.io/miden-docs/miden-tutorials/rust-client/counter_contract_tutorial.html) currently showcase the older, more verbose approach where the `initialize_client()` function is used in each code …

Adding client builder for simple initialization of the Rust client

---

CHANGELOG.md
crates/web-client/js/index.js
crates/web-client/js/workers/web-client-methods-worker.js
crates/web-client/package.json
crates/web-client/src/new_transactions.rs

This PR consolidates the `submit_transaction` and `submit_transaction_with_prover` calls exposed via WASM in the web client to just `submit_transaction`. 
I made this change because in https://github.com/0xPolygonMiden/miden-client/pull/720, I tried making it so that the top-level `WebClient` wrapper that I introduced to allow the web workers work only exposed one `submit_transaction` call with an optional prover. Then, depending on whether a `prover` was passed, it would call into `submit_transaction` or `submit_transaction_with_prover` as both of these calls were exposed from the rust side. The result of this could be confusing for consumers of the SDK because despite trying to consolidate the calls at the top level, the Typescript typings would still indicate that …

Web Client Submit Transaction Fix

---

Makefile

This change is meant to be temporary. The objective is to fix the CI checks while the node gets fixed and #793 gets merged.

fix: downgrade node

---

crates/rust-client/src/store/account.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/sqlite_store/account.rs
crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/store/sqlite_store/transaction.rs
crates/rust-client/src/store/web_store/account/js_bindings.rs
crates/rust-client/src/store/web_store/account/mod.rs
crates/rust-client/src/store/web_store/js/accounts.js
crates/rust-client/src/store/web_store/js/transactions.js
crates/rust-client/src/store/web_store/sync/mod.rs
crates/rust-client/src/store/web_store/transaction/mod.rs
crates/web-client/test/new_transactions.test.ts
tests/integration/main.rs

If a transaction gets discarded, delete. the corresponding account entry.  Due to the sync_nullifiers method from the web client store not supporting discarded transactions yet, this PR introduces the rollback only for the sqlite store.
part of #607

feat: rollback uncommitted tx

---

CHANGELOG.md
Cargo.lock
Makefile
crates/rust-client/Cargo.toml

- Updates the version of the node used in the CI and the Makefile.
- Updates the version of `miden-node-proto-build` to `0.8`.

chore: use miden-node's main, update miden-node-proto-build to 0.8

---

crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/sync/mod.rs
tests/integration/common.rs

The component PR had some flaky tests due to a value I modified while debugging and never returned to normal. I also removed some debug prints and changed the `wait_for_tx` to better catch these cases in the future.

fix: flaky tests

---

tests/integration/fpi_tests.rs

closes #824 
This PR adds an integration test with nested foreign procedure invocation. It also refactors the whole `fpi_tests.rs` file, moving some repeated logic to a deployment function.

test: nested foreign procedure invocation

---

CHANGELOG.md
crates/rust-client/src/errors.rs
crates/web-client/package.json
crates/web-client/src/models/note.rs
crates/web-client/src/models/note_metadata.rs
crates/web-client/src/models/note_type.rs
crates/web-client/src/new_transactions.rs
crates/web-client/test/new_transactions.test.ts
crates/web-client/test/webClientTestUtils.ts
crates/web-client/yarn.lock

This PR changes the web client's NoteType implementation to be an enum for easier consumption in TypeScript, as the static methods didn't work with type-checking e.g. NoteType.public() == NoteType.public() evaluates to false.
The main downside to this approach is that wasm enums can only have literal values, so we have to keep the underlying u8 values in line with the values defined in miden-lib

Convert NoteType class to enum

---

CHANGELOG.md
bin/miden-cli/src/commands/new_transactions.rs
docs/src/cli-reference.md

Currently, when prompting for transaction confirmation, both options are in uppercase; even though only one of them is the default. 
This PR underscores the "yes" option to indicate that it's not the default; thus making the CLI more aligned with other CLI tools.

chore: make non-default option lowercase when asking for confirmation

---

crates/rust-client/src/rpc/endpoint.rs

closes #844 
Adds support for final forward slash in endpoints.

fix: support final forward slash in endpoint

---

Cargo.lock
Cargo.toml
Makefile
bin/miden-cli/src/tests.rs
crates/rust-client/Cargo.toml
crates/rust-client/src/rpc/domain/account.rs
crates/rust-client/src/rpc/generated/nostd/requests.rs
crates/rust-client/src/rpc/generated/nostd/responses.rs
crates/rust-client/src/rpc/generated/nostd/transaction.rs
crates/rust-client/src/rpc/generated/std/requests.rs
crates/rust-client/src/rpc/generated/std/responses.rs
crates/rust-client/src/rpc/generated/std/transaction.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/transaction/mod.rs
crates/rust-client/src/transaction/request/foreign.rs
crates/web-client/package-lock.json
crates/web-client/yarn.lock

Refactors FPI-related changes after changes in witness data on base and node.

chore: Move to base's next

---

CHANGELOG.md
crates/web-client/src/import.rs
crates/web-client/test/import.test.ts

This PR adds the `import_account_by_id` functionality that was added in PR #733 to the WebClient. This resolves issue #855.
This PR makes it possible to import a public account on the WebClient:
```ts
const account = await client.importAccountById("0xb584c3769ab90b000004c780363668");
```
This function only works if the Account is public. Obviously this would only be used for public accounts that do not require authentication when submitting state changing transactions, i.e. a counter contract.
I added a test that deploys a public account, then deletes the store, then reimports it via the `importAccountById` method.
To run the tests:
1) Run the node locally by cloning the node repository, then run the following:
```
miden-node bundled bootstrap \
--data-directory data \ …
```

Export `import_account_by_id` to WebClient

---

Makefile
crates/rust-client/src/rpc/tonic_client/mod.rs

This PR updates the client to the miden-node https://github.com/0xPolygonMiden/miden-node/pull/790 changes.
The `get_notes_by_id` endpoint was returning the serialized notes in the `details` field, instead of serializing only the details. This PR updates the client to deserialize the details and use that to build the notes.

feat: read serialized note details

---

crates/rust-client/src/store/sqlite_store/account.rs
crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/store/web_store/account/mod.rs
crates/rust-client/src/store/web_store/sync/mod.rs

This PR addresses the final point in #663 by moving the account commitment missmatch check to the inside of the lock functions.

refactor: lock account check

---

crates/rust-client/src/rpc/domain/account.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/store/web_store/chain_data/mod.rs

`dead_code` is opaque in the sense that it is doesn't express the intention of the original author.
To make things more explicit most `dead_code`s were replaced with `cfg`s that indicate where they are actually used.

chore: Replace `dead_code` with intended usage.

---

CHANGELOG.md
bin/miden-cli/src/commands/init.rs
bin/miden-cli/src/config.rs
bin/miden-cli/src/lib.rs
bin/miden-cli/src/tests.rs
crates/rust-client/src/builder.rs
crates/rust-client/src/lib.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/sync/block_header.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/transaction/mod.rs
crates/web-client/src/lib.rs
docs/src/cli-config.md
docs/src/cli-reference.md
tests/integration/common.rs

This PR makes it possible to customize the number of blocks the client is behind the network.
Before this PR, the maximum number of blocks the client could be behind was hard-coded to be 256 blocks. Now, that difference can be set to any u32 or be ignored entirely.
The following changes were introduced:
- The current default maximum block difference is ignored (that is to say, it is set to `None`)
- `Client` struct:
- Received a new member `max_block_number_delta: Option<u32>`. This represents the number of blocks the client can be behind from the network in order for transactions and account proofs to be considered valid. If `None`, then the block difference is simply ignored.
- Its `new()` method now receives one additional argument of type `Option<u32>` used to set …

feat: Make the maximum block delta customizable from the client

---

CHANGELOG.md
crates/web-client/js/index.js
crates/web-client/package.json
crates/web-client/src/import.rs
crates/web-client/src/new_account.rs
crates/web-client/test/new_account.test.ts

This PR fixes a bug where users were not able to create new public accounts after importing their account from seed/wallet file. 
When creating a new account for an imported wallet, we first attempt to import an account with the seed to see if one exists. If one does not, we create one. However, we were storing the Falcon keys in the keystore on this import attempt, and thus when we tried to create a new account, the keys were already present in the store.

bug: Prevent  from adding to the keystore when import fails

---

Cargo.lock
Makefile
crates/rust-client/src/transaction/mod.rs
crates/rust-client/src/transaction/request/foreign.rs
crates/rust-client/src/transaction/request/mod.rs
tests/integration/fpi_tests.rs

This PR uses `tomyrd-update-base` as the node branch, we should update it to `next` once it's merged.

fix: update `miden-base` in client

---

.github/workflows/enforce-web-client-version-bump.yml
.github/workflows/publish-web-client-next.yml
CHANGELOG.md
Cargo.lock
scripts/detect-web-client-changes.sh

This PR adds two github actions that aid in improving the process of publishing the unstable version of the web client SDK to the npm registry. 
- **enforce-web-client-version-bump.yml**: this action runs on opened PRs or commits to those PRs. It checks if there have been changes in the `crates/web-client` or `crates/rust-client/src/store/web_client` folders. If there have been changes, it checks whether the version number in the `crates/web-client/package.json` file has been bumped. If it has been properly bumped or if there are no relevant changes that would merit a bump, the action passes. The action fails when changes are detected in those folders, but the `package.json` version has not been bumped.
- **publish-web-client-next.yml**: this action runs on pushes to the `next` branch. It …

Improve Web Client Publishing Flow on Next Branch

---

.github/workflows/web-docs-check.yml
Cargo.lock
Cargo.toml
Makefile
README.md
bin/miden-cli/README.md
crates/rust-client/Cargo.toml
crates/rust-client/src/transaction/mod.rs
crates/web-client/test/new_transactions.test.ts
docs/src/install-and-run.md
tests/integration/asm/custom_p2id.masm
tests/integration/custom_transactions_tests.rs

This PR brings the updates from https://github.com/0xMiden/miden-base/pull/1353 to the client.
One of the main changes is the introduction of the `SourceManager` for the executor. Right now we are just using the default implementation, but ideally we would use the source manager from the assembler used to compile code. The main problem with this is that generally we compile code with freshly instantiated assemblers each time (e.g. for account/note/transaction code) and we mostly don't have access to each one. 
We should look to refactor `miden-base` and `miden-client` to allow to share assemblers at every stage so that the used `SourceManager` can contain all the debug information.

feat: update Miden VM in client

---

CHANGELOG.md
crates/rust-client/Cargo.toml
crates/rust-client/src/rpc/tonic_client/api_client.rs
package.json

Relates to https://github.com/0xMiden/miden-node/issues/804 and https://github.com/0xMiden/miden-node/pull/844.
With https://github.com/0xMiden/miden-node/pull/844, we added support for ACCEPT headers in RPC requests to allow servers to match version requirements against clients that provide a valid header.
Update the RPC client to set the ACCEPT header based on the version in `Cargo.toml`.
Note that the server requires an exact major and minor version match (excluding patch).
There didn't appear to be any tests that use `new_client()` here so I haven't added any tests here. The code is more or less duplicate to that in miden-node which has comprehensive tests via https://github.com/0xMiden/miden-node/pull/844.
This does not update the WASM client.
I have not updated the docs because the …

feat: Add support for HTTP ACCEPT header version matching

---

Cargo.lock
Makefile
crates/rust-client/Cargo.toml
crates/rust-client/src/rpc/tonic_client/api_client.rs

Closes #921
We added server-side enforcement of ACCEPT headers in https://github.com/0xMiden/miden-node/pull/844.
We added support for HTTP ACCEPT header requests for the rust-client in #912.
We found that the web-client was already using the ACCEPT header by default. So we had to relax the enforcement of the header value in https://github.com/0xMiden/miden-node/pull/866.
In this PR, we are adding the HTTP ACCEPT header to web-client requests. The intention is to override the default web-client header found [here](https://github.com/devashishdxt/tonic-web-wasm-client/blob/75762cbc8777d4c493648983e94f014e25e6af6b/src/call.rs#L44-L46).

feat: Add HTTP ACCEPT header support to web client

---

CHANGELOG.md
crates/rust-client/src/rpc/mod.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/sqlite_store/mod.rs
crates/rust-client/src/test_utils/mock.rs

Relates to #849. Following on from this we could make the overall `Client` struct Sync with Send futures too.
In the past it has been impossible to use `TonicRpcClient` in a tokio task across await points because the futures returned by its implementation of `NodeRpcClient` were not `Send`.
Also the miden-client contains instances of `Box<dyn NodeRpcClient + Send>`. Because these trait objects are not `Sync`, their futures cannot be `Send`.
- Updated `TonicRpcClient` and `Store` traits to be subtraits of `Send` and `Sync`.
- Updated `TonicRpcClient` and `Store` trait functions to return futures which are `Send`.

feat: Add Send + Sync supertraits and add Send to futures return by dyn-compatible traits

---

bin/miden-cli/src/commands/sync.rs
bin/miden-cli/tests/cli.rs
crates/rust-client/src/rpc/mod.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/rust-client/src/store/sqlite_store/transaction.rs
crates/rust-client/src/store/web_store/transaction/mod.rs
crates/rust-client/src/store/web_store/transaction/utils.rs
crates/rust-client/src/sync/state_sync_update.rs
crates/rust-client/src/test_utils/mock.rs
crates/rust-client/src/transaction/mod.rs
docs/src/get-started/create-account-use-faucet.md

Found a couple of issues when testing the CLI with the released node:
1. The `miden sync` was not showing the new `new_public_notes` field.
2. Transactions were using the sync height to test for staleness but they should use submition height.

fix: various CLI issues

---

Cargo.lock

This PR refreshes `Cargo.lock` file in the `main` branch by running `cargo update`. The most important consequence of this is that winterfell dependency crates are now locked at v0.12.3.

Refresh Cargo.lock

---

Makefile
bin/miden-cli/Cargo.toml
bin/miden-cli/README.md
crates/rust-client/Cargo.toml
docs/src/get-started/create-account-use-faucet.md
docs/src/install-and-run.md
scripts/start-node-bg.sh

Updates the documentation to specify using lock files when installing/building. Addressing [this last comment](https://github.com/0xMiden/miden-node/issues/940#issuecomment-2958003501)

docs: locked install

---

Cargo.lock
Cargo.toml
Makefile
bin/miden-cli/tests/cli.rs
crates/rust-client/src/account/mod.rs
crates/rust-client/src/note/note_screener.rs
crates/rust-client/src/sync/tag.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transaction/mod.rs
crates/rust-client/src/transaction/request/builder.rs
crates/rust-client/src/transaction/request/mod.rs
crates/web-client/package.json
crates/web-client/src/models/note.rs
crates/web-client/src/models/note_tag.rs
crates/web-client/test/fpi.test.ts
docs/src/web-client/api/classes/NoteTag.md
tests/src/custom_transactions_tests.rs
tests/src/onchain_tests.rs

It seems that a `.once` test was accidentally added in https://github.com/0xMiden/miden-client/pull/958. This meant that the web tests were running that single test instead of the whole suite.

fix: remove `.once` from web test

---

CHANGELOG.md
bin/miden-cli/src/commands/new_transactions.rs
bin/miden-cli/src/lib.rs
bin/miden-cli/tests/cli.rs
crates/rust-client/src/builder.rs
crates/rust-client/src/test_utils/common.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transaction/request/builder.rs
crates/rust-client/src/transaction/request/mod.rs
crates/web-client/src/models/transaction_request/transaction_request_builder.rs
tests/src/custom_transactions_tests.rs
tests/src/fpi_tests.rs
tests/src/main_tests.rs
tests/src/network_transaction_tests.rs

stemming from https://github.com/0xMiden/miden-client/pull/1017#discussion_r2190629555
This PR removes the `with_` prefix from builders to better follow rust naming conventions and to simplify function names.

chore: remove `with_` prefix from builder functions

---

CHANGELOG.md
bin/miden-cli/src/commands/exec.rs
bin/miden-cli/src/errors.rs
bin/miden-cli/tests/cli.rs
crates/rust-client/src/lib.rs
crates/rust-client/src/note/mod.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transaction/mod.rs
crates/web-client/src/notes.rs
crates/web-client/src/transactions.rs
tests/src/custom_transactions_tests.rs
tests/src/fpi_tests.rs

This small PR exports the newly added `ScriptBuilder` from miden-base. This PR will close #944 since the functionality is now in the `ScriptBuilder`.
This PR also changes `.nonce_increment()` to `.nonce_delta()` since this method changed in miden-base.

Export `ScriptBuilder` from miden-base

---

Cargo.toml
bin/miden-cli/Cargo.toml
crates/rust-client/Cargo.toml
crates/testing/node-builder/Cargo.toml
crates/testing/prover/Cargo.toml
crates/web-client/Cargo.toml
tests/Cargo.toml

closes #988 
In this PR I ran `cargo sort --grouped --workspace` to do a general workspace modification but I belive most of the ordering issues were already fixed by `make toml` using `taplo`. I also created sections inside each dependency section.

chore: add dependency categories

---

bin/miden-cli/README.md
bin/miden-cli/src/commands/init.rs

Docs were out of date, with https://github.com/0xMiden/miden-client/issues/877 the `--network` argument is mandatory.

chore: update `init` cmd docs

---

bin/miden-cli/src/commands/exec.rs

Clap ignores the newlines from `ExecCMD::input_paths`'s doc-comment. This hinders the comments' readability. 
This PR adds the `#[clap(verbatim_doc_comment)]` over  `ExecCMD::input_paths` in order for the displayed comment to follow the formatting.
For reference, here's the before and after:
Before:
```
$~ miden-client exec --help
Execute the specified program against the specified account
(...)
-i, --inputs-path <INPUTS_PATH>
Path to the inputs file. This file will be used as inputs to the VM's advice map.
The file should contain a TOML array of inline tables, where each table has two fields: - `key`: a 256-bit hexadecimal string representing a word to be used as a key for the input entry. The hexadecimal value must be prefixed with 0x. - `values`: an array of 64-bit unsigned integers …
```

chore: add verbatim_doc_comment in ExecCmd::inputs_path

---

crates/rust-client/src/lib.rs

This PR reexports `hex_to_bytes` and `ToHex` from `miden_tx::utils`. This is needed in https://github.com/0xMiden/miden-faucet/pull/11

feat: add `hex_to_bytes` utils reexport

---

CHANGELOG.md
Cargo.lock
crates/rust-client/Cargo.toml
crates/rust-client/src/sync/block_header.rs
crates/web-client/Cargo.toml

Closes #1073
The problem was that because of [the way that MMR changes are applied during the sync state](https://github.com/0xMiden/miden-client/blob/next/crates/rust-client/src/sync/state_sync.rs#L474), and the fact that block $N$ stores the peaks for block $N-1$, we were essentially passing more data than needed to the `PartialMmr::from_parts()` (which is unsafe and does not check inputs). Then, on later additions, `PartialMmr::add` had some sanity `debug_assertions` for making sure that nodes that are supposed to be new were not there before. I could not find a way to easily sanitize these inputs in a way that did not trigger the problem (and that did not forfeit the ability of just getting all MMR nodes from the store which is more convenient and performant), but found a workaround …

fix: Avoid passing unneeded nodes to `PartialMmr::from_parts`

---

crates/web-client/src/models/note_inputs.rs
crates/web-client/src/models/note_recipient.rs
crates/web-client/src/models/note_script.rs

This PR adds more note getters available in `rust-client` that were not yet available in the `web-client`.
This is needed to show eg. note inputs (raw and decoded in case of well-known notes), note scripts roots, etc in the context of a dApp.

feat(web-client): expose more note getters in the web-client

---

Makefile

While setting up the repo for contributing, I noticed the `check-tools` command to verify the presence of `cargo-nextest` was wrong and thus always returning that it was missing.

fix: cargo-nextest check-tools command

---

Cargo.lock
crates/rust-client/src/account/mod.rs

This PR adds a reexport for `FungibleFaucetExt` and bumps the `miden-base` rev to `1a977c41031f6c4eb705892c03dddd21992ac83f`. I didn't bump it to the last one because we need to update the node before to avoid compilation errors.

feat: reexport `FungibleFaucetExt`

---

crates/rust-client/src/store/data_store.rs
crates/rust-client/src/store/sqlite_store/account.rs
crates/rust-client/src/store/sqlite_store/store.sql
crates/rust-client/src/tests.rs

This PR fixes a bug where empty storage maps were deserialized from the store as value slots. It also adds a test for this specific case.

fix: empty map bug

---

crates/rust-client/src/errors.rs

When `TransactionExecutorError` is displayed in a trace, the error is showed twice. For example:
```
Caused by:
0: transaction executor error: failed to execute transaction kernel program:
× error during processing of event in on_event handler
╰─▶ public note with metadata NoteMetadata { sender: V0(AccountIdV0 { prefix: 11226098615840309536, suffix: 9029612700626841344 }), note_type: Public, tag: LocalAny(3874619392), aux: 0,
execution_hint: Always } and recipient digest 0x0000000000000000000000000000000000000000000000003b1cfd38897a99ba is missing details in the advice provider
1: failed to execute transaction kernel program:
× error during processing of event in on_event handler
╰─▶ public note with metadata NoteMetadata { sender: V0(AccountIdV0 { prefix: 11226098615840309536, suffix: …
```

feat: remove duplicate error trace

---

crates/rust-client/src/lib.rs

This PR reeports the hashing function `Rpo256` from miden-objects.

feat: reexport `Rpo256`

---

CHANGELOG.md
bin/integration-tests/src/tests/onchain.rs
crates/rust-client/src/rpc/errors.rs
crates/rust-client/src/rpc/mod.rs
crates/rust-client/src/rpc/tonic_client/mod.rs

Closes #935. Also does some other smaller refactors like changing up some error variants.
As long as the node does not return more structured errors (sort of related: https://github.com/0xMiden/miden-node/issues/1106), we can't do without parsing the incoming message and giving it some more context in relation to the client (aka, basically all that can fail right now is either version not being compatible and genesis commitment not matching up). If somehow the message drifts away from what the node returns, the test should catch it.

refactor: RPC errors

---

crates/web-client/package.json
crates/web-client/playwright.config.ts
crates/web-client/test/playwright.global.setup.ts

After setting up playwright, there was a misconfiguration that caused the tests that had to be run with the remote prover to be run as if the remote prover wasn't specified. The issue was a missing env var in the package.json.

tests: restore remote prover tests

---

bin/integration-tests/src/tests/network_transaction.rs
crates/rust-client/Cargo.toml
crates/rust-client/src/lib.rs

- manually construct the `Note`
- remove dependency on `miden-lib/testing` feature
- minor cleanups of the network transaction integration test (define library once, define script once)
closes https://github.com/0xMiden/miden-client/issues/1236

chore: replace `NoteBuilder` by manually constructing the note

---

crates/rust-client/src/builder.rs
crates/rust-client/src/lib.rs
crates/rust-client/src/sync/state_sync.rs

`NodeRpcClient` is already `Send`

chore: remove redundant `Send` bound

---

CHANGELOG.md
crates/rust-client/src/transaction/request/mod.rs

Needed for multisig support:
```rust
pub async fn new_multisig_transaction(
&mut self,
account: Account,
mut transaction_request: TransactionRequest,
transaction_summary: TransactionSummary,
signatures: Vec<Option<Vec<Felt>>>,
) -> Result<TransactionResult, MultisigClientError> {
// Add signatures to the advice provider
let advice_inputs = transaction_request.advice_map_mut(); // <----------- need this
let msg = transaction_summary.to_commitment();
let num_approvers: u32 = account.storage().get_item(0).unwrap().as_elements()[1]
.try_into()
.unwrap();
for i in 0..num_approvers as usize {
let pub_key_index_word = Word::from([Felt::from(i as u32), ZERO, ZERO, ZERO]);
let pub_key = account
.storage()
.get_map_item(1, pub_key_index_word)
.unwrap();
let sig_key = Hasher::merge(&[pub_key, msg]); …
```

feat: Add a mutable getter for `TransactionRequest`'s advice map

---

CHANGELOG.md
crates/rust-client/src/account/mod.rs

If my application relies only on the `miden-client` dependency (i.e. not on `miden-lib`), I'd like the ability to use all the different auth component types, not just `AuthRpoFalcon512`
can be patch released

chore: re-export all auth components from miden-lib
