src/cli/account.rs
src/lib.rs
src/store/mod.rs
src/store/store.sql

Rename keys table

---

src/store/mod.rs

Changes de/serialization of `NoteScript` type, which no longer serializes with `serde` derive.

fix: NoteScript serialization

---

src/mock.rs
src/store/mod.rs
src/store/transactions.rs

Following recent changes (https://github.com/0xPolygonMiden/miden-base/pull/360), this PR fixes our code accordingly

fix: Fix nullifiers after `miden-base` update

---

src/cli/input_notes.rs
src/client/accounts.rs
src/client/notes.rs
src/client/sync_state.rs
src/client/transactions.rs
src/errors.rs
src/mock.rs
src/store/accounts.rs
src/store/mock_executor_data_store.rs
src/store/notes.rs
src/store/state_sync.rs
src/store/store.sql
src/store/transactions.rs
src/tests.rs

Closes #73
After some breaking changes in the base crates, we needed to update the code accordingly.

fix: Fixing build after changes from the dependencies

---

Cargo.toml
src/client/transactions.rs

Updates note creation functions after https://github.com/0xPolygonMiden/miden-base/pull/411
TODO:

refactor: Update note creation

---

src/client/sync_state.rs
src/mock.rs
src/store/chain_data.rs
src/store/state_sync.rs

There are further changes incoming as part of #114 (related to the `TODO` I added), but for now this fixes the build after https://github.com/0xPolygonMiden/miden-node/pull/173 was merged.

fix: Fix build after `block_path` changes

---

src/cli/input_notes.rs
src/client/sync.rs

To merge after https://github.com/0xPolygonMiden/miden-node/issues/218 is closed

chore: Remove outdated warning, add comment

---

Cargo.toml
README.md
src/cli/account.rs
src/client/rpc_client.rs
src/client/sync.rs
src/client/transactions.rs
src/mock.rs

In this PR I propose a fix to the breaking changes brought by the changes to the node proto in this commit: https://github.com/0xPolygonMiden/miden-node/commit/db51f392257abcf2fd5a703a15b830e4d8a5f7ab

Fix node breaking changes in proto

---

src/store/sqlite_store/chain_data.rs
src/store/sqlite_store/store.sql

refactor: Remove unused table fields

---

README.md
docs/cli.md

addresses [this comment](https://github.com/0xPolygonMiden/miden-client/issues/191#issuecomment-1986145581) on #191

docs: update readme and mkdocs regarding admitting partial note ids

---

Cargo.toml
src/cli/account.rs
src/cli/input_notes.rs
src/cli/mod.rs
src/cli/transactions.rs
src/client/accounts.rs
src/client/chain_data.rs
src/client/mod.rs
src/client/notes.rs
src/client/rpc/mod.rs
src/client/rpc/tonic_client.rs
src/client/sync.rs
src/client/transactions.rs
src/errors.rs
src/mock.rs
src/store/data_store.rs
src/store/mock_executor_data_store.rs
src/store/mod.rs
src/store/sqlite_store/accounts.rs
src/store/sqlite_store/chain_data.rs
src/store/sqlite_store/mod.rs
src/store/sqlite_store/notes.rs
src/store/sqlite_store/sync.rs
src/store/sqlite_store/transactions.rs
src/tests.rs
tests/integration/main.rs

Updates dependencies to pull from published crates. 
TODO:

chore: Update dependencies and remove mock dependency

---

Cargo.toml

Adds description to `Cargo.toml`

docs: `Cargo.toml` description

---

CHANGELOG.md
src/cli/transactions.rs
src/client/transactions.rs
tests/integration/main.rs

feat: add P2IDR tx

---

Cargo.toml
src/cli/transactions.rs
src/client/accounts.rs
src/client/rpc/mod.rs
src/client/rpc/tonic_client.rs
src/client/sync.rs
src/client/transactions/mod.rs
src/client/transactions/transaction_request.rs
src/errors.rs
src/mock.rs
src/store/mod.rs
src/store/note_record/input_note_record.rs
src/store/note_record/output_note_record.rs
src/store/sqlite_store/mod.rs
src/store/sqlite_store/sync.rs
src/tests.rs
tests/integration/main.rs

Adds support for on chain notes.

feat: Implement `GetNotesById` RPC endpoint

---

CHANGELOG.md
Cargo.toml
README.md
docs/cli.md
miden-client.toml
src/cli/init.rs
src/cli/mod.rs
src/config.rs

feat: add init command

---

docs/cli-reference.md
src/cli/tags.rs
src/client/sync.rs
src/store/mod.rs
src/store/sqlite_store/mod.rs
src/store/sqlite_store/store.sql
src/store/sqlite_store/sync.rs
src/tests.rs
tests/integration/main.rs

refactor: note tag rework

---

Makefile.toml

Cherry picks the fix from #293

fix: update CI commands after node binary and dir changes (#293)

---

Cargo.toml
src/store/sqlite_store/chain_data.rs
src/store/sqlite_store/mod.rs

feat: use rarray extension for sqlite

---

CHANGELOG.md
docs/cli-config.md
docs/cli-reference.md
src/cli/account.rs
src/cli/mod.rs
src/cli/transactions.rs
src/config.rs
src/store/sqlite_store/mod.rs

feat: default accounts

---

docs/cli-reference.md

Removes the testnet url and replace it with its ip

fix: change cli-reference url to ip

---

README.md

The old site is not used anymore.

docs: Point to updated site

---

CHANGELOG.md
docs/cli-reference.md
src/cli/info.rs
src/cli/notes.rs
src/client/sync.rs
src/store/data_store.rs
src/store/mod.rs
src/store/note_record/input_note_record.rs
src/store/note_record/mod.rs
src/store/note_record/output_note_record.rs
src/store/sqlite_store/notes.rs
src/store/sqlite_store/store.sql
src/tests.rs
tests/integration/cli_tests.rs
tests/integration/main.rs

adresses [this comment](https://github.com/0xPolygonMiden/miden-client/pull/355#discussion_r1623175663).

chore: rename pending notes to expected notes

---

CHANGELOG.md
src/client/rpc/mod.rs
src/client/rpc/tonic_client.rs
src/client/sync.rs
src/client/transactions/mod.rs
src/store/mod.rs
src/store/sqlite_store/sync.rs
src/store/sqlite_store/transactions.rs
tests/integration/main.rs

feat: use transaction summary and nullifier update from sync response

---

src/client/transactions/mod.rs

I noticed while going through code that we had some ignored code.

refactor: delete code replaced by transaction authenticator

---

docs/install-and-run.md
tests/integration/main.rs

chore: remove repetitive words

---

crates/rust-client/Cargo.toml
tests/Cargo.toml

This PR points the library/cli dependecies to v0.4 of `miden-base`

feat: update `miden-base` to v0.4

---

CHANGELOG.md
Cargo.toml
Makefile
crates/rust-client/src/mock.rs
crates/rust-client/src/notes/mod.rs
crates/rust-client/src/store/data_store.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/note_record/input_note_record.rs
crates/rust-client/src/store/note_record/output_note_record.rs
crates/rust-client/src/store/sqlite_store/notes.rs
crates/rust-client/src/store/sqlite_store/store.sql
crates/rust-client/src/store/sqlite_store/sync.rs
crates/rust-client/src/store/web_store/notes/utils.rs
crates/rust-client/src/store/web_store/sync/mod.rs
crates/rust-client/src/sync/block_headers.rs
crates/rust-client/src/sync/mod.rs
tests/integration/main.rs

Fix build and integrate changes from https://github.com/0xPolygonMiden/miden-base/pull/810.
Also adds `default-members` to workspace to not have `cargo build` break due to conflicting default features.
(Made by @tomyrd)

fix: Build errors

---

bin/miden-cli/src/commands/tags.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/notes/mod.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/transactions/mod.rs
tests/integration/custom_transactions_tests.rs
tests/integration/onchain_tests.rs
tests/integration/swap_transactions_tests.rs

Fix `next` branch updating with https://github.com/0xPolygonMiden/miden-base/pull/812

fix: use `NoteExecutionMode` instead of `NoteExecutionHint`

---

Makefile

Closes #460 
This was address in #459 but it was re-introduced by mistake.

docs(Makefile): Use 1st person in Makefile comments

---

CHANGELOG.md
bin/miden-cli/src/commands/export.rs
bin/miden-cli/src/tests.rs

feat: account export in CLI

---

tests/config/miden-node.toml

docs: Update integration tests config file

---

CHANGELOG.md
docs/cli-config.md
docs/cli-reference.md

Hello
While looking through your docs I found and fixed several typos errors.
Br, Elias.

docs: fix spelling issues

---

CHANGELOG.md
crates/web-client/src/models/mod.rs
crates/web-client/src/models/sync_summary.rs
crates/web-client/src/sync.rs

Exposing the full SyncSummary object from the web client `sync_state` for use in the Chrome wallet

feat: Expose full SyncSummary from web client

---

crates/rust-client/src/transactions/mod.rs

To merge after https://github.com/0xPolygonMiden/miden-base/pull/952

test: Fix account builder usage

---

docs/cli-config.md
docs/cli-reference.md
docs/design.md
docs/library.md

Some small changes I made while reviewing the documentation.

fix: v0.6 documentation

---

Makefile

Regarding the changes from https://github.com/0xPolygonMiden/miden-base/pull/955 , updates the Makefile to use the new CLI instead of the old worker binary.

fix: update Makefile to use the prover CLI

---

Makefile

addresses [this comment](https://github.com/0xPolygonMiden/miden-client/pull/562#discussion_r1829544006)

refactor: separate makefile commands for prover and node build

---

crates/rust-client/src/lib.rs
crates/rust-client/src/tests.rs
tests/integration/main.rs

Changed some of the testing functions to make it clear that they are only meant for testing

fix: remove testing functions

---

CHANGELOG.md
crates/rust-client/src/notes/import.rs
crates/rust-client/src/tests.rs

feat: add check for processing notes

---

crates/web-client/src/lib.rs

Addresses https://github.com/0xPolygonMiden/miden-client/pull/599#discussion_r1849313559

refactor: rename `proving_url`

---

CHANGELOG.md
bin/miden-cli/src/commands/new_transactions.rs
bin/miden-cli/src/tests.rs

feat: add support for unauthenticated notes consumption in CLI

---

CHANGELOG.md
crates/rust-client/src/notes/import.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/note_record/input_note_record/mod.rs
crates/rust-client/src/store/note_record/input_note_record/states/committed.rs
crates/rust-client/src/store/note_record/input_note_record/states/consumed_authenticated_local.rs
crates/rust-client/src/store/note_record/input_note_record/states/consumed_external.rs
crates/rust-client/src/store/note_record/input_note_record/states/consumed_unauthenticated_local.rs
crates/rust-client/src/store/note_record/input_note_record/states/expected.rs
crates/rust-client/src/store/note_record/input_note_record/states/invalid.rs
crates/rust-client/src/store/note_record/input_note_record/states/mod.rs
crates/rust-client/src/store/note_record/input_note_record/states/processing_authenticated.rs
crates/rust-client/src/store/note_record/input_note_record/states/processing_unauthenticated.rs
crates/rust-client/src/store/note_record/input_note_record/states/unverified.rs
crates/rust-client/src/store/sqlite_store/mod.rs
crates/rust-client/src/store/sqlite_store/notes.rs
crates/rust-client/src/store/web_store/mod.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/transactions/mod.rs

fix: CLI `miden notes` bugs 

---

Makefile

This PR fixes the integration tests in the main branch. The node created in the CI run should be the one in main and not next.

fix: main CI

---

Cargo.lock
crates/rust-client/src/accounts.rs
crates/rust-client/src/lib.rs
crates/rust-client/src/notes/import.rs
crates/rust-client/src/notes/mod.rs
crates/rust-client/src/store/note_record/input_note_record/states/mod.rs
crates/rust-client/src/sync/block_headers.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/sync/tags.rs
crates/rust-client/src/transactions/mod.rs

addresses #626 and #453 
In this PR I mostly concentrated on user facing documentation, addressing the documentation changes mentioned in #626 and going through public structs to check that they are documented.

chore: improve client documentation

---

CHANGELOG.md
crates/rust-client/src/tests.rs
crates/rust-client/src/transactions/script_builder.rs

feat: add support for notes without asset in transctions

---

CHANGELOG.md
Cargo.lock
Makefile
bin/miden-cli/Cargo.toml
bin/miden-cli/README.md
docs/install-and-run.md
tests/README.md

chore: remove testing feature from cli

---

Makefile
bin/miden-cli/src/commands/import.rs
bin/miden-cli/src/commands/init.rs

fix: improve command info messages

---

CHANGELOG.md
Cargo.lock
bin/miden-cli/src/commands/init.rs
bin/miden-cli/src/tests.rs
crates/rust-client/src/rpc/endpoint.rs
docs/cli-reference.md
docs/install-and-run.md

feat: add CNAMEd networks to CLI

---

docs/get-started/create-account-use-faucet.md

Changing the URL of the testnet faucet to the new and correct one.

Changing faucet url in tutorial

---

bin/miden-cli/src/tests.rs

test: add test for CLI with testnet

---

Cargo.lock
bin/miden-cli/src/commands/new_account.rs
bin/miden-cli/src/commands/new_transactions.rs
crates/rust-client/src/account/mod.rs
crates/rust-client/src/mock.rs
crates/web-client/src/lib.rs
crates/web-client/src/models/provers.rs

Also fixes mock after recent block changes

fix: Build after template typing merged on base

---

Cargo.lock
bin/miden-cli/src/tests.rs
crates/rust-client/src/account/mod.rs
crates/rust-client/src/mock.rs
crates/rust-client/src/rpc/domain/block.rs
crates/rust-client/src/store/data_store.rs
crates/rust-client/src/store/sqlite_store/chain_data.rs
crates/rust-client/src/sync/block_header.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transaction/mod.rs
crates/rust-client/src/transaction/request/mod.rs
crates/web-client/src/models/block_header.rs
crates/web-client/src/utils/test_utils.rs
tests/integration/common.rs
tests/integration/fpi_tests.rs

Addresses errors after https://github.com/0xPolygonMiden/miden-base/pull/1210

fix: client build

---

CHANGELOG.md
bin/miden-cli/src/tests.rs
crates/rust-client/src/sync/mod.rs
tests/config/miden-client-rpc.toml
tests/integration/common.rs
tests/integration/fpi_tests.rs

This PR fixes a bug found when executing the integration tests against devnet. It also updates the cli tests so they use the rpc config file.

fix: devnet tests bugs

---

Cargo.lock
crates/rust-client/Cargo.toml
crates/rust-client/src/rpc/generated/nostd/rpc.rs
crates/rust-client/src/rpc/generated/std/rpc.rs

The following dependencies were updated:

chore: Update dependencies

---

CHANGELOG.md
crates/web-client/src/account.rs
docs/src/web-client/api/classes/WebClient.md
docs/src/web-client/examples/accounts.md
docs/src/web-client/examples/export.md
docs/src/web-client/examples/import.md
docs/src/web-client/examples/index.md
docs/src/web-client/examples/new-accounts.md
docs/src/web-client/examples/new-transactions.md
docs/src/web-client/examples/notes.md
docs/src/web-client/examples/sync.md
docs/src/web-client/examples/tags.md
docs/src/web-client/examples/transactions.md

Follow up from https://github.com/0xPolygonMiden/miden-client/pull/808. Adding concrete examples for the web client SDK api.

Web Client Mdbook Examples

---

.github/workflows/docs.yml
scripts/check-docs.sh

chore: add check for documentation changes in CI

---

crates/rust-client/src/store/sqlite_store/chain_data.rs
crates/rust-client/src/store/web_store/chain_data/mod.rs
crates/rust-client/src/store/web_store/sync/mod.rs

feat: replace tuples with structs

---

bin/miden-cli/src/commands/account.rs
bin/miden-cli/src/commands/init.rs
bin/miden-cli/src/config.rs
crates/rust-client/src/rpc/endpoint.rs

feat: remove network from CliConfig

---

.github/workflows/web-docs-check.yml
CHANGELOG.md
Cargo.toml
README.md
bin/miden-cli/README.md
crates/rust-client/src/rpc/domain/account.rs
crates/rust-client/src/store/web_store/chain_data/mod.rs
crates/web-client/package-lock.json
crates/web-client/package.json
crates/web-client/src/import.rs
crates/web-client/src/new_account.rs
crates/web-client/test/import.test.ts
crates/web-client/test/new_account.test.ts
crates/web-client/test/webClientTestUtils.ts
crates/web-client/yarn.lock
docs/src/install-and-run.md
docs/src/web-client/api/classes/WebClient.md

Some changes in the web client were merged directly to main, this PR looks to bring those changes to next so that we can test that everything works together and so that we can fix most conflicts before release.

Merge `main` into `next`

---

Cargo.lock
crates/rust-client/src/note/note_screener.rs
crates/rust-client/src/rpc/generated/nostd/note.rs
crates/rust-client/src/rpc/generated/nostd/requests.rs
crates/rust-client/src/rpc/generated/nostd/responses.rs
crates/rust-client/src/rpc/generated/nostd/transaction.rs
crates/rust-client/src/rpc/generated/std/note.rs
crates/rust-client/src/rpc/generated/std/requests.rs
crates/rust-client/src/rpc/generated/std/responses.rs
crates/rust-client/src/rpc/generated/std/transaction.rs
crates/rust-client/src/rpc/tonic_client/mod.rs
crates/testing/node-builder/Cargo.toml
crates/testing/node-builder/src/lib.rs
tests/integration/onchain_tests.rs

Adds (and fixes) a test for network transactions
Should be merged after https://github.com/0xMiden/miden-node/pull/881

feat: add test for network transactions

---

CHANGELOG.md
Cargo.lock
Makefile
bin/miden-cli/Cargo.toml
crates/rust-client/Cargo.toml
crates/rust-client/README.md
crates/rust-client/src/rpc/generated/nostd/responses.rs
crates/rust-client/src/rpc/generated/std/responses.rs
docs/src/library.md
tests/Cargo.toml

feat: merge `concurrent` with `std`

---

CHANGELOG.md
crates/rust-client/src/transaction/request/builder.rs
crates/rust-client/src/transaction/request/mod.rs
tests/src/custom_transactions_tests.rs

feat: add transaction script argument support

---

CHANGELOG.md
bin/miden-cli/src/lib.rs
crates/rust-client/src/builder.rs
crates/rust-client/src/lib.rs
crates/rust-client/src/note/note_screener.rs
crates/rust-client/src/store/mod.rs
crates/rust-client/src/store/sqlite_store/chain_data.rs
crates/rust-client/src/store/sqlite_store/mod.rs
crates/rust-client/src/store/web_store/chain_data/mod.rs
crates/rust-client/src/store/web_store/mod.rs
crates/rust-client/src/sync/block_header.rs
crates/rust-client/src/test_utils/common.rs
crates/rust-client/src/tests.rs
crates/rust-client/src/transaction/mod.rs
crates/rust-client/src/transaction/request/mod.rs
tests/src/main_tests.rs

feat: introduce enums instead of bool

---

crates/rust-client/src/sync/block_header.rs

Fixes the errors mentioned in [this comment](https://github.com/0xMiden/miden-client/pull/1037#issuecomment-3123408857)

fix: next build

---

Cargo.lock
Cargo.toml
bin/miden-cli/Cargo.toml
crates/rust-client/Cargo.toml
crates/rust-client/src/store/data_store.rs
crates/rust-client/src/transaction/mod.rs

@igamigo changes required for https://github.com/0xMiden/miden-base/pull/1666

draft: async experimental compat changes

---

crates/web-client/yarn.lock
docs/src/web-client/examples/export.md
docs/src/web-client/examples/import.md
docs/src/web-client/examples/mock.md
docs/src/web-client/examples/rpc_client.md
docs/src/web-client/examples/transactions.md

docs: update web client docs

---

crates/rust-client/src/note/import.rs

fix: include current block in note import check

---

CHANGELOG.md
crates/rust-client/src/lib.rs
crates/rust-client/src/note/mod.rs
crates/rust-client/src/note/note_screener.rs
crates/rust-client/src/sync/mod.rs
crates/rust-client/src/transaction/mod.rs
crates/testing/miden-client-tests/src/tests/transaction.rs

feat: shared source manager for error reporting

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/web-client/package.json
crates/web-client/src/models/address.rs
crates/web-client/yarn.lock
docs/src/web-client/api/classes/Address.md

fix: do not take ownership of account_id
